import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import { useState, useCallback } from "react";

const inter = Inter({ subsets: ["latin"] });

const Graph = {};

export default function Home() {
  const [audioCtx, _] = useState<AudioContext | null>(
    typeof window !== "undefined" ? new AudioContext() : null
  );
  console.log(audioCtx);

  const handleClick = () => {
    addNode();
  };

  const addNode = useCallback(() => {
    if (audioCtx) {
      const gainNode = audioCtx.createGain();
      const oscNode = audioCtx.createOscillator();
      oscNode.frequency.setValueAtTime(440, audioCtx.currentTime);

      oscNode.connect(gainNode).connect(audioCtx.destination);
      oscNode.start();

      console.log(gainNode, oscNode);
    }
  }, [audioCtx]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <button onClick={handleClick}>DO IT</button>
      </main>
    </>
  );
}
