import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import { useState, useCallback } from "react";
import Draggable from "react-draggable";
// import { useSvgDrawing } from "@svg-drawing/react";

const inter = Inter({ subsets: ["latin"] });

const Graph = {};

type NodeProps = {
  name: string;
};

const Node = ({ name }: NodeProps) => {
  return (
    <Draggable handle=".handle">
      <div>
        <div
          className="handle"
          style={{ width: "20px", height: "10px", backgroundColor: "blue" }}
        ></div>
        <div>{name}</div>
      </div>
    </Draggable>
  );
};

type INode = {
  name: String;
  node: AudioNode;
  settings: object;
  inputs: INode[];
  outputs: INode[];
};

const connections: [INode, INode][] = [];

export default function Home() {
  const [audioCtx, _] = useState<AudioContext | null>(
    typeof window !== "undefined" ? new AudioContext() : null
  );
  console.log(audioCtx);

  const handleClick = () => {
    addNode();
  };

  const handleAddNode = () => {};

  const addNode = useCallback(() => {
    if (audioCtx) {
      const gainNode = audioCtx.createGain();
      const oscNode = audioCtx.createOscillator();
      oscNode.frequency.setValueAtTime(440, audioCtx.currentTime);

      oscNode.connect(gainNode).connect(audioCtx.destination);
      oscNode.start();

      console.log(gainNode, oscNode);
    }
  }, [audioCtx]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <button onClick={handleAddNode}>Add Node</button>
        <Draggable>
          <div>
            <button onClick={handleClick}>DO IT</button>
          </div>
        </Draggable>
        <Node name="test" />
      </main>
    </>
  );
}
